
#This make file is used to set up a simple way to run the server/client.

#To run the server
server:
	java -classpath out/production/Sistemas-Distribuidos-Projeto app.ServerApp

#To run the client
client:
	java -classpath out/production/Sistemas-Distribuidos-Projeto app.client.Client
