
server:
	java -classpath /home/joao/Desktop/Distributed-Systems-Project/Projeto-SD/out/production/Sistemas-Distribuidos-Projeto app.ServerApp

client:
	java -classpath /home/joao/Desktop/Distributed-Systems-Project/Projeto-SD/out/production/Sistemas-Distribuidos-Projeto app.client.Client
